---
{{ if (.Values.ingress.enabled) }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "plone.fullname" . }}-crt
spec:
  secretName: {{ index .Values.ingress.tls 0 }} {{ .secretName }}
  dnsNames:
  - {{ .Values.http.frontend_server }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.http.frontend_server }}
  issuerRef:
    name: {{ index .Values.ingress.tls 0 }} {{ .clusterIssuer}}
    kind: ClusterIssuer
{{ end }}
