---
{{ if (.Values.ingress.enabled) }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "plone.fullname" . }}-crt
spec:
  secretName: {{ with index .Values.ingress.tls 0 }}{{ .secretName }}{{ end }}
  dnsNames:
  {{- with .Values.ingress.hosts }}
{{ toYaml . | indent 4 }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      {{- with index .Values.ingress.hosts }}
{{ toYaml . | indent 8 }}
      {{- end }}
  issuerRef:
    name: {{ with index .Values.ingress.tls 0 }}{{ .clusterIssuer  }}{{ end }}
    kind: ClusterIssuer
{{ end }}
