---
{{ if (.Values.ingress.enabled) }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: plone-crt
spec:
  secretName: plone-crt-secret
  dnsNames:
  - {{ .Values.http.frontend_server }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.http.frontend_server }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{ end }}
