apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "plone.fullname" . }}-db
  labels:
    app: {{ template "plone.name" . }}-db
    chart: {{ template "plone.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "plone.name" . }}-db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "plone.name" . }}-db
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: db
              containerPort: 5432
              protocol: TCP
{{ if (.Values.volumes.db) }}
          volumeMounts:
            - mountPath: "/var/lib/postgresql"
              name: plone-volume1
{{ end }}
          env:
{{ toYaml .Values.db.env | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.db.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{ if (.Values.volumes) and (.Values.volumes.db.pv) }}
    {{- with .Values.volumes.db.pv }}
      volumes:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
