apiVersion: v1
kind: Service
metadata:
  name: {{ template "plone.fullname" . }}-db
  labels:
    app: {{ template "plone.name" . }}-db
    chart: {{ template "plone.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: http
  selector:
    app: {{ template "plone.name" . }}-db
    release: {{ .Release.Name }}
