apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: {{ template "plone.fullname" . }}-app
    labels:
      app: {{ template "plone.name" . }}
      chart: {{ template "plone.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    type: {{ .Values.service.type }}
    ports:
      - port: {{ .Values.service.port }}
        nodePort: {{ .Values.service.nodePort}}
        name: http
    selector:
      app: {{ template "plone.name" . }}-app
      release: {{ .Release.Name }}
- kind: Service
  apiVersion: v1
  metadata:
    name: {{ template "plone.fullname" . }}-http
    labels:
      app: {{ template "plone.name" . }}-http
      chart: {{ template "plone.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  spec:
    type: {{ .Values.service.type }}
    ports:
      - port: 80
        name: http
    selector:
      app: {{ template "plone.name" . }}-app
      release: {{ .Release.Name }}
