{{ if (.Values.volumes.d) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "plone.fullname" . }}-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
{{ end }}
