version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.1-r1 curl curl-dev openssl
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application
          command: |
            cd images/plone ; docker build --cache-from=app -t app .
      - run:
          name: Build NGINX
          command: |
            cd images/nginx ; docker build -t plone.nginx .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run: 
          command: curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | sh
      - run:
          name: helm lint for minikube
          command: |
            cd helm; helm lint plone-stack -f plone-stack/values-minikube.yaml
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               echo "not pushing for master"
            elif [ ! -z $CIRCLE_TAG ]; then
               docker tag app sahlinet/plone:$CIRCLE_TAG
               docker tag plone.nginx sahlinet/plone.nginx:$CIRCLE_TAG
               docker push sahlinet/plone:$CIRCLE_TAG
               docker push sahlinet/plone.nginx:$CIRCLE_TAG
            else
               echo "pushing tag dev"
               docker tag app sahlinet/plone:dev
               docker tag plone.nginx sahlinet/plone.nginx:dev
               docker push sahlinet/plone:dev
               docker push sahlinet/plone.nginx:dev
               env
            fi
            docker images
workflows:
  version: 2
  test:
    jobs:
      - build:
          context: docker-hub
          filters:
            branches:
              only:
                - master
                - develop
                - gh-pages
  release:
    jobs:
      - build:
          context: docker-hub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+$/
