db:
  image: philipsahli/postgresql-test
  ports:
   - "5432"
  environment:
   - DB_NAME=plone
   - DB_USER=plone
   - PASSWORD=plonepw
   - SUPERUSER=true
plone:
  build: .
  ports:
      - "8888:8080"
  environment:
   - DB_NAME=plone
   - DB_USER=plone
   - PASSWORD=plonepw
   - SUPERUSER=true
  links:
   - db
