apiVersion: v1
entries:
  plone-stack:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-09-27T09:36:38.838025398+02:00
    description: A Helm chart for Plone Stack
    digest: e20762c5ba5dcc53db2f96c1ebedc5f834836501f47daab43be6d36e301a2957
    name: plone-stack
    urls:
    - https://sahlinet.github.io/plone-stack/helm/plone-stack/plone-stack-0.1.9.tgz
    version: 0.1.9
generated: 2018-09-27T09:36:38.837357558+02:00
