apiVersion: v1
entries:
  plone-stack:
  - apiVersion: v1
    appVersion: "5.1"
    created: 2018-10-15T21:52:48.805118964+02:00
    description: A Helm chart for Plone Stack
    digest: b208a8c3db23263c09f7e6daf02ee84c359836b38682e1f4665db36b9d3404cb
    maintainers:
    - email: philip@sahli.net
      name: Philip Sahli
      url: https://twitter.com/philipsahli
    name: plone-stack
    urls:
    - https://sahlinet.github.io/plone-stack/helm/plone-stack/plone-stack-0.1.17.tgz
    version: 0.1.17
generated: 2018-10-15T21:52:48.80433321+02:00
